/* This file was generated by syncqt. */
#ifndef QT_QTQMLTC_VERSION_H
#define QT_QTQMLTC_VERSION_H

#define QTQMLTC_VERSION_STR "6.11.2"

#define QTQMLTC_VERSION 0x0601102

#endif // QT_QTQMLTC_VERSION_H
