// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef ASTRO_VERSION_H
#define ASTRO_VERSION_H

#define ASTRO_VERSION_STRING "26.08.0"
#define ASTRO_VERSION_MAJOR 26
#define ASTRO_VERSION_MINOR 8
#define ASTRO_VERSION_PATCH 0
#define ASTRO_VERSION ((26<<16)|(8<<8)|(0))

#endif
