// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef MARBLE_VERSION_H
#define MARBLE_VERSION_H

#define MARBLE_VERSION_STRING "26.08.0"
#define MARBLE_VERSION_MAJOR 26
#define MARBLE_VERSION_MINOR 8
#define MARBLE_VERSION_PATCH 0
#define MARBLE_VERSION ((26<<16)|(8<<8)|(0))

#endif
