[Paths]
Prefix=../
Documentation=doc
Headers=include
Libraries=lib
LibraryExecutables=bin
Binaries=bin
Plugins=plugins
QmlImports=qml
ArchData=.
Data=.
Translations=translations
Examples=examples
Tests=tests
Settings=etc/xdg
HostPrefix=../../../../../../tmp/claude-0/-home-user-winlibs/f343f3a4-6c75-5ecd-a050-15e02fa072aa/scratchpad/qt-host-6.11.2
HostBinaries=bin
HostLibraries=lib
HostLibraryExecutables=libexec
HostData=../../../../../../home/user/winlibs/qt/6.11.2
Sysroot=
SysrootifyPrefix=false
TargetSpec=win32-g++
HostSpec=linux-g++
