#!/bin/bash
# Qt 6.11.2 for 64-bit Windows (mingw-w64 cross build).
# Modules: qtbase, qtsvg, qtimageformats, qtserialport, qt5compat.
# Requires build-qt-host.sh to have been run first (QT_HOST_PATH).
# OpenSSL support is linked against the repo's openssl build.
source "$(dirname "$0")/env.sh"

VER=6.11.2
PREFIX="$REPO_ROOT/qt/$VER"
HOST_PREFIX="$WORK/qt-host-$VER"
OPENSSL="$REPO_ROOT/openssl/openssl-3.5.8"

export WINLIBS_FIND_ROOT="$OPENSSL"

MODULES="qtshadertools qtdeclarative qtsvg qtimageformats qtserialport qt5compat"
for m in qtbase $MODULES; do
    if [ ! -d "$SRC/$m-$VER" ]; then
        git clone --depth 1 --branch "v$VER" "https://github.com/qt/$m.git" "$SRC/$m-$VER"
    fi
done

# --- qtbase (skipped if already installed) ---
if [ ! -f "$PREFIX/lib/cmake/Qt6/qt.toolchain.cmake" ]; then
B="$BLD/qt-cross-qtbase"
rm -rf "$B"
cmake -G Ninja -S "$SRC/qtbase-$VER" -B "$B" \
    -DCMAKE_TOOLCHAIN_FILE="$TOOLCHAIN_FILE" \
    -DQT_HOST_PATH="$HOST_PREFIX" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$PREFIX" \
    -DQT_BUILD_EXAMPLES=OFF -DQT_BUILD_TESTS=OFF \
    -DQT_FEATURE_dbus=OFF \
    -DINPUT_openssl=linked \
    -DOPENSSL_ROOT_DIR="$OPENSSL" \
    -DQT_FEATURE_sql_odbc=ON -DQT_FEATURE_sql_sqlite=ON
cmake --build "$B" -j"$JOBS"
cmake --install "$B"
fi

# --- add-on modules (use the toolchain file generated by the qtbase install) ---
QT_TOOLCHAIN="$PREFIX/lib/cmake/Qt6/qt.toolchain.cmake"
for m in $MODULES; do
    B="$BLD/qt-cross-$m"
    rm -rf "$B"
    EXTRA=""
    if [ "$m" = qtdeclarative ]; then
        # svgtoqml would require host qtsvg+svgtoqml; skip the QML
        # VectorImage support instead.
        EXTRA="-DQT_FEATURE_quick_vectorimage=OFF"
    fi
    cmake -G Ninja -S "$SRC/$m-$VER" -B "$B" \
        -DCMAKE_TOOLCHAIN_FILE="$QT_TOOLCHAIN" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX="$PREFIX" \
        -DQT_BUILD_EXAMPLES=OFF -DQT_BUILD_TESTS=OFF \
        $EXTRA
    cmake --build "$B" -j"$JOBS"
    cmake --install "$B"
done

strip_prefix "$PREFIX"
echo "Qt $VER (Windows x64) installed to $PREFIX"
